name = "embed.rs"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = "The site theme for embed.rs"
homepage = "http://embed.rs/"
min_version = 0.17

[author]
  name = "Marc Brinkmann"
  homepage = "http://marcbrinkmann.de"
