title: embed.rs
description: "embed.rs is a community around embedded development using Rust on bare-metal MCUs"
baseurl: ""

# external info
url: "http://embed.rs"
github_username:  embed-rs

# currently, most contributors are located in Germany
timezone: Europe/Berlin
encoding: utf-8

# Build settings
markdown: kramdown
permalink: pretty
